version: '3'

networks:
    LEMP:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: scc_nginx
        ports:
            - "8080:80"
        volumes:
            - public:/public
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - LEMP

    mariaDB:
        image: mariadb:latest
        container_name: scc_mariaDB
        volumes:
            - ./db.fixures:/var/lib/mysql:rw
        ports:
            - "3306:3306"
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=654321          
        networks:
            - LEMP    

    app:
        build: .
        container_name: scc_app
        volumes:
            -./:./app
        ports:
            - "9000:9000"       
        networks:
            - LEMP

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: scc_phpMyAdmin
        ports:
            - "8183:80"
        environment:        
            PMA_ARBITRARY: 1
        depends_on:
            - mariaDB
        networks:
            - LEMP
 
